In [3]:
# Notes

#import numpy
import numpy as np

#create array from list
lst = [1,2,3]
arr = np.array(lst)
print(arr)

#sum
arr2 = arr+1
print(arr2)

#mult
arr3 = arr2*5
print(arr3)

[1 2 3]
[2 3 4]
[10 15 20]


In [19]:
#arange: Return evenly spaced values within a given interval.
#similar to range python
from0To50Every2 = np.arange(0,50,2,np.int16) #data type will be int16

#linspace: Return evenly spaced numbers over a specified interval.
from0To10 = np.linspace(0,10,50,True,False)
print(from0To10)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [29]:
#eturn a new array of given shape and type, filled with zeros or ones. 
print( np.zeros((5,5)) )
print( np.ones((6,18)) )

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [63]:
#multi dimensional array
arr_2d = np.array([[1,2,4],[3,4,3]])

#Use shape to know how many columns and rows the arr has.
arr_2d.shape #arr_2d will return 2,3

arr_3d = np.array(  [[1,2],[2,-22],[2,1],[3,0]] )
arr_3d.shape #arr_3d will return 4,2

#size: how many elements the array contains
arr_2d.size

#max and min
arr_2d.max()
arr_3d.min()

arr_3d.max(axis=1) # will return the max of every row
arr_3d.min(axis=0) # will return the min of every column

array([  1, -22])

In [82]:
#reshape

arr_2d = np.arange(9) # [1,2,3,4,5,6,7,8,9]
arr_2d_reshaped = arr_2d.reshape(3,3)
print(arr_2d_reshaped) # [1,2,3],[4,5,6],[6,7,8]

#slicing
arr_2d_reshaped[:2,:2] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1],
       [3, 4]])